name: Publish create-neha-app

on:
  push:
    branches: [ main ]
    paths:
      - 'create-neha-app/**'
      - '.github/workflows/publish-create-neha-app.yml'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: create-neha-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --no-audit --progress=false
          fi
      - name: Determine if publish is needed
        id: check
        shell: bash
        run: |
          PKG_NAME=$(node -p "require('./package.json').name")
          PKG_VER=$(node -p "require('./package.json').version")
          echo "Package: $PKG_NAME@$PKG_VER"
          PUBLISHED_VER=$(npm view "$PKG_NAME@$PKG_VER" version || true)
          if [ "$PUBLISHED_VER" = "$PKG_VER" ]; then
            echo "Already published"
            echo "publish=false" >> $GITHUB_OUTPUT
          else
            echo "publish=true" >> $GITHUB_OUTPUT
          fi
      - name: Publish to npm
        if: steps.check.outputs.publish == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
