name: Publish create-neha-app

on:
  push:
    branches: [ main ]
    paths:
      - 'create-neha-app/**'
      - '.github/workflows/publish-create-neha-app.yml'
      - 'create-neha-app/.releaserc*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: create-neha-app
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - name: Release (semantic-release)
        run: npx -y -p semantic-release -p @semantic-release/changelog -p @semantic-release/git -p @semantic-release/npm -p @semantic-release/github -p @semantic-release/commit-analyzer -p @semantic-release/release-notes-generator semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
