name: (Deprecated) Publish create-neha-app (use release.yml)

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is deprecated. Use release.yml"
